web_geo/peta/urls.py
from django.urls import path
from .views import HomePageView, point_datasets

app_name = 'peta'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('data/', point_datasets, name='data'),
]

web_geo/web_geo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('peta.urls', namespace='peta')),
    path('admin/', admin.site.urls),
]

web_geo/peta/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.gis.db import models


class Point(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=50)
    points = models.PointField(srid=4326)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Points"

# Create your models here.

web_geo/peta/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core.serializers import serialize
from django.http import HttpResponse
from .models import Point

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'index.html'


def point_datasets(request):
    points = serialize('geojson', Point.objects.all())
    return HttpResponse(points, content_type='json')

web_geo/web_geo/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

web_geo/templates/base.html
{% load static %}
{% load leaflet_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% include "snippets/styles.html" %}
	<title>
		{% block Title %}
			
		{% endblock Title %}
	</title>
</head>
<body>
	{% include "snippets/navbar.html" %}
<div class="container " style="margin-top:70px">
	{% block Heading %}
		
	{% endblock Heading %}

	{% block Contents %}
		
	{% endblock Contents %}
</div>
	{% include "snippets/scripts.html" %}
</body>
</html>

web_geo/templates/index.html
{% extends "base.html" %}
{% load leaflet_tags %}

{% block Title %}
	WebGis Geofisika
{% endblock Title %}

{% block Heading %}
	<h1>Geofisika</h1>
{% endblock Heading %}

{% block Contents %}
<script>
	function map_layers(map,option){
		var datasets = new L.GeoJSON.AJAX("{% url 'peta:data' %}",{
			onEachFeature: function(feature, layer){
				layer.bindPopup(feature.properties.name.toString());
			}
		});
		datasets.addTo(map);
	}
</script>
	{% leaflet_map "gis" callback="window.map_layers" %}
{% endblock Contents %}

web_geo/templates/snippets/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-secondary">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img  src="{% static "img/logo.png" %}" height="40px" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Maps</a>
        </li>
      </ul>
      <div class="nav-item dropdown ml-auto">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Create Maps</a>
          <a class="dropdown-item" href="#">Manage Maps</a>
        </div>
      </div>
    </div>
  </div>
</nav>  

web_geo/templates/snippets/scripts.html
{% load static %}

<script src="{% static "vendor/jquery/jquery.js" %}"></script>
<script src="{% static "vendor/popper/popper.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>

web_geo/templates/snippets/styles.html
{% load static %}
{% load leaflet_tags %}

{% leaflet_js %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
<style>#gis {height: 500px}</style>
<script src="{% static "vendor/leaflet/leaflet.ajax.js" %}"></script>